import { getNewerFile, getUrlsJson } from "../utils/file_handling.js";

// Function to prompt user for input
async function promptUser(question: string): Promise<string> {
  const readline = await import("readline");
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

// Function to get GitHub username from API
async function getGitHubUsername(token: string): Promise<string> {
  const axios = await import("axios");

  try {
    const response = await axios.default.get("https://api.github.com/user", {
      headers: {
        Authorization: `Bearer ${token}`,
        "User-Agent": "brebaje-cli",
        Accept: "application/vnd.github.v3+json",
      },
    });

    return response.data.login;
  } catch (error: any) {
    console.error(
      "❌ Failed to fetch GitHub username:",
      error.response?.data?.message || error.message,
    );
    throw error;
  }
}

// Function to get original repository from forked repository
async function getOriginalRepository(
  forkedOwner: string,
  forkedRepo: string,
  forkedRepoUrl: string,
  token: string,
): Promise<{ originalOwner: string; originalRepo: string }> {
  const axios = await import("axios");

  let originalOwner: string;
  let originalRepo: string;

  try {
    const repoResponse = await axios.default.get(
      `https://api.github.com/repos/${forkedOwner}/${forkedRepo}`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          "User-Agent": "brebaje-cli",
          Accept: "application/vnd.github.v3+json",
        },
      },
    );

    if (repoResponse.data.fork && repoResponse.data.parent) {
      // This is a fork, use the parent as the original repository
      originalOwner = repoResponse.data.parent.owner.login;
      originalRepo = repoResponse.data.parent.name;
    } else {
      // This is not a fork, so it might be the original repository itself
      // In this case, we can't create a PR (you can't create PR to yourself)
      throw new Error(`Repository ${forkedRepoUrl} is not a fork. Cannot create pull request.`);
    }
  } catch (error: any) {
    if (error.response?.status === 404) {
      throw new Error(
        `Repository ${forkedRepoUrl} not found or not accessible with provided token.`,
      );
    }
    throw error;
  }

  return { originalOwner, originalRepo };
}

// Function to create gist (existing functionality)
async function createGist(
  recordFile: string,
  recordContent: string,
  index: number,
  token: string,
): Promise<string> {
  const axios = await import("axios");

  console.log(`🔗 Creating public gist for social sharing...`);

  const gistData = {
    description: `Powers of Tau Contribution Record - Index ${index}`,
    public: true,
    files: {
      [recordFile]: {
        content: recordContent,
      },
    },
  };

  const response = await axios.default.post("https://api.github.com/gists", gistData, {
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
      "User-Agent": "brebaje-cli",
      Accept: "application/vnd.github.v3+json",
    },
  });

  return response.data.html_url;
}

// Function to generate response_resume.md content
function generateResponseResume(
  contributorName: string,
  githubUsername: string,
  index: number,
  power: number,
  recordFile: string,
  hardwareInfo?: string,
): string {
  const currentDate = new Date().toISOString().split("T")[0];
  const recordFileName = recordFile;

  return `# Contribution Response Resume

## Contributor Information
- **Name**: ${contributorName}
- **GitHub Username**: ${githubUsername}
- **Contribution Date**: ${currentDate}
- **Contribution Index**: ${index}
- **Ceremony Power**: ${power}

## Files
- **Record File**: \`${recordFileName}\`

## Hardware Information
${hardwareInfo || "Not provided"}

## Verification
This contribution was made using the brebaje-cli tool and follows the Cardano Perpetual Powers of Tau ceremony protocol.

---
*Generated by brebaje-cli*
`;
}

// Function to create repository contribution
async function createRepositoryContribution(
  contributorName: string,
  githubUsername: string,
  index: number,
  power: number,
  recordFile: string,
  recordContent: string,
  hardwareInfo: string | undefined,
  repositoryUrl: string,
  token: string,
): Promise<string> {
  const axios = await import("axios");

  console.log(`📁 Creating repository contribution...`);

  // Parse repository URL to get owner and repo
  const repoMatch = repositoryUrl.match(/github\.com\/([^\/]+)\/([^\/]+)$/);
  if (!repoMatch) {
    throw new Error(`Invalid repository URL format: ${repositoryUrl}`);
  }

  const [, owner, repo] = repoMatch;
  const folderName = `${index.toString().padStart(4, "0")}_${githubUsername}_response`;

  // Create record file in repository
  const recordPath = `${folderName}/${recordFile}`;
  const recordFileData = {
    message: `Add contribution record for ${contributorName} (index ${index})`,
    content: Buffer.from(recordContent).toString("base64"),
  };

  await axios.default.put(
    `https://api.github.com/repos/${owner}/${repo}/contents/${recordPath}`,
    recordFileData,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "brebaje-cli",
        Accept: "application/vnd.github.v3+json",
      },
    },
  );

  console.log(`✅ Record file uploaded: ${recordPath}`);

  // Generate response_resume.md content
  const resumeContent = generateResponseResume(
    contributorName,
    githubUsername,
    index,
    power,
    recordFile,
    hardwareInfo,
  );

  // Create response_resume.md file in repository
  const resumePath = `${folderName}/response_resume.md`;
  const resumeFileData = {
    message: `Add response resume for ${contributorName} (index ${index})`,
    content: Buffer.from(resumeContent).toString("base64"),
  };

  await axios.default.put(
    `https://api.github.com/repos/${owner}/${repo}/contents/${resumePath}`,
    resumeFileData,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "brebaje-cli",
        Accept: "application/vnd.github.v3+json",
      },
    },
  );

  console.log(`✅ Response resume uploaded: ${resumePath}`);

  return `https://github.com/${owner}/${repo}/tree/main/${folderName}`;
}

// Function to create pull request from fork to original repository
async function createPullRequest(
  contributorName: string,
  githubUsername: string,
  ceremonyIndex: number,
  folderName: string,
  forkedRepoUrl: string,
  token: string,
): Promise<string> {
  const axios = await import("axios");

  console.log(`🔄 Creating pull request to original ceremony repository...`);

  // Parse forked repository URL to get owner and repo
  const forkedMatch = forkedRepoUrl.match(/github\.com\/([^\/]+)\/([^\/]+)$/);
  if (!forkedMatch) {
    throw new Error(`Invalid forked repository URL format: ${forkedRepoUrl}`);
  }

  const [, forkedOwner, forkedRepo] = forkedMatch;

  // Get original repository information
  const { originalOwner, originalRepo } = await getOriginalRepository(
    forkedOwner,
    forkedRepo,
    forkedRepoUrl,
    token,
  );

  // Create pull request data
  const prData = {
    title: `Contribution record: ${contributorName} (index ${ceremonyIndex})`,
    head: `${githubUsername}:main`, // From user's fork main branch
    base: "main", // To original repository main branch
    body: `## Cardano Perpetual Powers of Tau - Contribution Record

### Contributor Information
- **Name**: ${contributorName}
- **GitHub Username**: @${githubUsername}
- **Contribution Index**: ${ceremonyIndex}
- **Contribution Folder**: \`${folderName}/\`

### Files Included
- \`${folderName}/pot*_${ceremonyIndex.toString().padStart(4, "0")}_record.txt\` - Official contribution record
- \`${folderName}/response_resume.md\` - Contributor metadata and hardware information

### Verification
This contribution was made using the brebaje-cli tool and follows the Cardano Perpetual Powers of Tau ceremony protocol.

The contribution record can be independently verified and this PR adds the official documentation to the ceremony repository.

---
*Automatically generated by brebaje-cli*`,
  };

  // Create the pull request
  const prResponse = await axios.default.post(
    `https://api.github.com/repos/${originalOwner}/${originalRepo}/pulls`,
    prData,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        "User-Agent": "brebaje-cli",
        Accept: "application/vnd.github.v3+json",
      },
    },
  );

  return prResponse.data.html_url;
}

export async function postRecordPerpetualPowersOfTau(githubToken?: string): Promise<void> {
  try {
    console.log(`📤 Posting contribution record...`);

    const fs = await import("fs");
    const path = await import("path");

    // Check if output directory exists
    const outputDir = "output";
    if (!fs.existsSync(outputDir)) {
      console.error(`❌ Error: Output directory does not exist: ${outputDir}`);
      console.error(`Please make a contribution first using the contribute command.`);
      process.exit(1);
    }

    // Get the newest record file
    const recordFile = getNewerFile(outputDir, "_record.txt");

    if (recordFile === null) {
      console.error(`❌ Error: No record files found in ${outputDir} directory`);
      console.error(`Please make a contribution first using the contribute command.`);
      process.exit(1);
    }

    // Validate record file format
    const match = recordFile.match(/pot(\d+)_(\d+)_record\.txt/);
    if (!match) {
      console.error(`❌ Error: Invalid record file format: ${recordFile}`);
      console.error(`Expected format: pot<power>_<index>_record.txt`);
      process.exit(1);
    }

    const power = parseInt(match[1]);
    let index = parseInt(match[2]);

    // Try to find ceremony URLs JSON file in input directory to get the correct index
    let ceremonyIndex = index; // fallback to record file index

    try {
      const ceremonyUrlsPath = getUrlsJson("input");
      const ceremonyUrlsContent = fs.readFileSync(ceremonyUrlsPath, "utf-8");
      const ceremonyUrls = JSON.parse(ceremonyUrlsContent);

      // Extract index from upload_info.field_name (e.g., "pot10_0013.ptau" -> 0013)
      if (ceremonyUrls.upload_info && ceremonyUrls.upload_info.field_name) {
        const uploadMatch = ceremonyUrls.upload_info.field_name.match(/pot\d+_(\d+)\.ptau/);
        if (uploadMatch) {
          ceremonyIndex = parseInt(uploadMatch[1]);
          console.log(`📋 Using ceremony index ${ceremonyIndex} from ceremony URLs file`);
        }
      }
    } catch (error) {
      // getUrlsJson throws and exits on critical errors, so this handles JSON parsing errors
      console.warn(`⚠️ Could not parse ceremony URLs file, using index from record file: ${index}`);
    }

    const recordFilePath = path.join(outputDir, recordFile);
    console.log(`Found record file: ${recordFile}`);

    // Read the record file content
    const recordContent = fs.readFileSync(recordFilePath, "utf-8");

    // Get tokens from environment
    const gistToken = githubToken || process.env.GITHUB_TOKEN;
    const repoToken = process.env.GITHUB_TOKEN_SCOPED;
    const repositoryUrl = process.env.CEREMONY_REPOSITORY_URL;

    // Validate required tokens and configuration
    if (!gistToken) {
      console.error(`🔑 GitHub classic token required for gist creation.`);
      console.error(`You can provide it by:`);
      console.error(`  1. Setting GITHUB_TOKEN environment variable`);
      console.error(`  2. Using: brebaje-cli setup gh-token <your-classic-token>`);
      console.error(`  3. Create a classic token at: https://github.com/settings/tokens`);
      console.error(`     (Select 'gist' scope only)`);
      process.exit(1);
    }

    if (!repoToken) {
      console.error(`🔑 GitHub fine-grained token required for repository operations.`);
      console.error(`You can set it up by:`);
      console.error(`  1. Using: brebaje-cli setup gh-token-scoped <your-fine-grained-token>`);
      console.error(`  2. Create a fine-grained token at: https://github.com/settings/tokens`);
      console.error(
        `     (Scope to your forked ceremony repository with Contents + PR permissions)`,
      );
      process.exit(1);
    }

    if (!repositoryUrl) {
      console.error(`🏗️ Ceremony repository URL required.`);
      console.error(`You can set it up by:`);
      console.error(`  1. Using: brebaje-cli setup ceremony-repo <your-forked-repo-url>`);
      console.error(`     Example: https://github.com/your-username/ceremony-repo-fork`);
      process.exit(1);
    }

    // Get GitHub username from scoped token
    let githubUsername: string;
    try {
      githubUsername = await getGitHubUsername(repoToken);
      console.log(`👤 GitHub username: ${githubUsername}`);
    } catch (error) {
      console.error(`❌ Failed to get GitHub username. Please check your fine-grained token.`);
      process.exit(1);
    }

    // Prompt user for contributor name
    console.log(`\n📝 Please provide your information for the contribution record:`);
    const contributorName = await promptUser("Enter your full name: ");

    if (!contributorName) {
      console.error(`❌ Contributor name is required.`);
      process.exit(1);
    }

    // Optional: Prompt for hardware information
    const hardwareInfo = await promptUser(
      "Enter hardware information (optional, press Enter to skip): ",
    );

    console.log(`\n🚀 Starting dual posting workflow...`);

    let gistUrl: string;
    let repositoryContributionUrl: string;
    let pullRequestUrl: string | null = null;

    try {
      // Create gist for social sharing
      gistUrl = await createGist(recordFile, recordContent, ceremonyIndex, gistToken);
      console.log(`✅ Gist created: ${gistUrl}`);

      // Create repository contribution
      repositoryContributionUrl = await createRepositoryContribution(
        contributorName,
        githubUsername,
        ceremonyIndex,
        power,
        recordFile,
        recordContent,
        hardwareInfo || undefined,
        repositoryUrl,
        repoToken,
      );
      console.log(`✅ Repository contribution created: ${repositoryContributionUrl}`);

      // Create pull request to original repository
      try {
        const folderName = `${ceremonyIndex.toString().padStart(4, "0")}_${githubUsername}_response`;
        pullRequestUrl = await createPullRequest(
          contributorName,
          githubUsername,
          ceremonyIndex,
          folderName,
          repositoryUrl,
          repoToken,
        );
        console.log(`✅ Pull request created: ${pullRequestUrl}`);
      } catch (prError: any) {
        console.warn(`⚠️ Could not create pull request automatically: ${prError.message}`);
        console.warn(`💡 You can manually create a PR from your fork to the original repository.`);
        pullRequestUrl = null;
      }
    } catch (error: any) {
      if (error.response) {
        const status = error.response.status;
        const message = error.response.data?.message || "Unknown error";

        if (status === 401) {
          console.error(`❌ Authentication Error: Invalid GitHub token`);
          console.error(`Please check your tokens have correct permissions`);
        } else if (status === 403) {
          console.error(`❌ Permission Error: Token lacks required permissions`);
          console.error(
            `Gist token needs 'gist' scope, repository token needs 'Contents' and 'Pull requests'`,
          );
        } else if (status === 404) {
          console.error(`❌ Not Found Error: Check repository URL and token permissions`);
        } else if (status === 422) {
          console.error(`❌ Validation Error: ${message}`);
          console.error(`This might mean the file already exists or path is invalid`);
        } else {
          console.error(`❌ GitHub API Error (${status}): ${message}`);
        }
      } else if (error.request) {
        console.error(`❌ Network Error: Cannot reach GitHub API`);
        console.error(`Please check your internet connection`);
      } else {
        console.error(`❌ Request Error: ${error.message}`);
      }

      console.error(`💡 You can manually create files at:`);
      console.error(`   Gist: https://gist.github.com/`);
      console.error(`   Repository: ${repositoryUrl}`);
      process.exit(1);
    }

    // Get ceremony URL (original repository) for social sharing
    let ceremonyUrl = repositoryUrl; // fallback to fork URL
    try {
      const repoMatch = repositoryUrl.match(/github\.com\/([^\/]+)\/([^\/]+)$/);
      if (repoMatch) {
        const [, forkedOwner, forkedRepo] = repoMatch;
        const { originalOwner, originalRepo } = await getOriginalRepository(
          forkedOwner,
          forkedRepo,
          repositoryUrl,
          repoToken,
        );
        ceremonyUrl = `https://github.com/${originalOwner}/${originalRepo}`;
      }
    } catch (error) {
      console.warn(
        `⚠️ Could not determine original ceremony repository, using fork URL for social sharing.`,
      );
    }

    // Enhanced social media sharing with repository, gist, and PR links
    let tweetText = `🎉 Contributed to Cardano Perpetual Powers of Tau Ceremony!

📋 Official ceremony: ${ceremonyUrl}
👁️ Quick view: ${gistUrl}`;
    `

#Cardano #ZK #Catalyst`;
    const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`;

    console.log(`\n🎊 Success! Your contribution has been posted:`);
    console.log(`📋 Official repository: ${repositoryContributionUrl}`);
    console.log(`👁️ Public gist (social): ${gistUrl}`);
    if (pullRequestUrl) {
      console.log(`🔄 Pull request: ${pullRequestUrl}`);
    }
    console.log(`📊 Contribution Index: ${ceremonyIndex}`);
    console.log(`👤 Contributor: ${contributorName} (${githubUsername})`);
    console.log(`💡 All links verify your contribution publicly.`);

    console.log(`\n🐦 Share on Twitter/X:`);
    console.log(`${twitterUrl}`);
    console.log(`\n📱 Click the link above to share your contribution on social media!`);
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    console.error("❌ Failed to post contribution record:", errorMessage);
    process.exit(1);
  }
}
