packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - "@nestjs/core"
  - "@scarf/scarf"
  - "@swc/core"
  - nx
  - sqlite3
  - unrs-resolver
onlyBuiltDependencies:
  - aws-sdk
  - bufferutil
  - chacha-native
  - core-js
  - core-js-pure
  - esbuild
  - node-datachannel
  - utf-8-validate
  - utp-native
