/* eslint-disable tsdoc/syntax */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: "category",
      label: "Explanation",
      items: [{ type: "autogenerated", dirName: "explanation" }],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
    {
      type: "category",
      label: "Reference",
      items: [{ type: "autogenerated", dirName: "api" }],
    },
    {
      type: "category",
      label: "Security & Operations",
      items: [{ type: "autogenerated", dirName: "security" }],
    },
  ],
};

module.exports = sidebars;
