CREATE TYPE "ceremonyState" AS ENUM (
  'SCHEDULED',
  'OPENED',
  'PAUSED',
  'CLOSED',
  'CANCELED',
  'FINALIZED'
);

CREATE TYPE "ceremonyType" AS ENUM (
  'PHASE1',
  'PHASE2'
);

CREATE TYPE "circuitTimeoutType" AS ENUM (
  'DYNAMIC',
  'FIXED',
  'LOBBY'
);

CREATE TYPE "participantStatus" AS ENUM (
  'CREATED',
  'WAITING',
  'READY',
  'CONTRIBUTING',
  'CONTRIBUTED',
  'DONE',
  'FINALIZING',
  'FINALIZED',
  'TIMEDOUT',
  'EXHUMED'
);

CREATE TYPE "participantContributionStep" AS ENUM (
  'DOWNLOADING',
  'COMPUTING',
  'UPLOADING',
  'VERIFYING',
  'COMPLETED'
);

CREATE TABLE "projects" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "contact" varchar,
  "coordinatorId" int NOT NULL
);

CREATE TABLE "ceremonies" (
  "projectId" int NOT NULL,
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "description" varchar,
  "state" "ceremonyState",
  "start_date" int,
  "end_date" int,
  "penalty" int,
  "authProviders" json
);

CREATE TABLE "circuits" (
  "ceremonyId" int NOT NULL,
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "timeoutMechanismType" "circuitTimeoutType",
  "dynamicThreshold" int,
  "fixedTimeWindow" int,
  "sequencePosition" int,
  "zKeySizeInBytes" int,
  "constraints" int,
  "pot" int,
  "averageContributionComputationTime" int,
  "averageFullContributionTime" int,
  "averageVerifyContributionTime" int,
  "compiler" json,
  "template" json,
  "verification" json,
  "artifacts" json,
  "metadata" json,
  "files" json
);

CREATE TABLE "contributions" (
  "circuitId" int NOT NULL,
  "participantId" int NOT NULL,
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contributionComputationTime" int,
  "fullContributionTime" int,
  "verifyContributionTime" int,
  "zkeyIndex" int,
  "valid" boolean,
  "lastUpdated" int,
  "files" json,
  "verificationSofware" json,
  "beacon" json
);

CREATE TABLE "participants" (
  "userId" int NOT NULL,
  "ceremonyId" int NOT NULL,
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" "participantStatus",
  "contributionStep" "participantContributionStep",
  "contributionProgress" int,
  "contributionStartedAt" int,
  "verificationStartedAt" int,
  "tempContributionData" json,
  "timeout" json
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "displayName" varchar,
  "creationTime" int,
  "lastSignInTime" int,
  "lastUpdated" int,
  "avatarUrl" int,
  "provider" varchar
);

COMMENT ON COLUMN "projects"."name" IS 'title in the frontend';

COMMENT ON COLUMN "projects"."contact" IS 'E.g.: nicoserranop (Discord)';

COMMENT ON COLUMN "ceremonies"."description" IS 'description in the frontend';

COMMENT ON COLUMN "ceremonies"."authProviders" IS 'check auth providers classes';

COMMENT ON COLUMN "participants"."timeout" IS 'Array of timeouts. Check Timeout class';

ALTER TABLE "projects" ADD FOREIGN KEY ("coordinatorId") REFERENCES "users" ("id");

ALTER TABLE "ceremonies" ADD FOREIGN KEY ("projectId") REFERENCES "projects" ("id");

ALTER TABLE "circuits" ADD FOREIGN KEY ("ceremonyId") REFERENCES "ceremonies" ("id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("circuitId") REFERENCES "circuits" ("id");

ALTER TABLE "contributions" ADD FOREIGN KEY ("participantId") REFERENCES "participants" ("id");

ALTER TABLE "participants" ADD FOREIGN KEY ("userId") REFERENCES "users" ("id");

ALTER TABLE "participants" ADD FOREIGN KEY ("ceremonyId") REFERENCES "ceremonies" ("id");
