import { config as dotenvConfig } from "dotenv";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

// Global configuration interface
export interface BrebajeConfig {
  // API Configuration
  BREBAJE_API_URL: string;
  BREBAJE_AUTH_TOKEN_PATH: string;

  // Contributor Information
  CONTRIBUTOR_NAME?: string;

  // GitHub Tokens
  GITHUB_TOKEN?: string;
  GITHUB_TOKEN_SCOPED?: string;

  // AWS Configuration
  AWS_ACCESS_KEY_ID?: string;
  AWS_SECRET_ACCESS_KEY?: string;
  AWS_REGION: string;

  // S3 Configuration
  S3_BUCKET: string;
  S3_PREFIX: string;

  // Ceremony Configuration
  CEREMONY_POWER: string;
  CEREMONY_ELLIPTIC_CURVE: string;
  CEREMONY_REPOSITORY_URL?: string;
}

// Default configuration values
const DEFAULT_CONFIG: BrebajeConfig = {
  BREBAJE_API_URL: "http://localhost:3000",
  BREBAJE_AUTH_TOKEN_PATH: "~/.brebaje/token", // TODO: We can later encrypt the tokens.
  AWS_REGION: "us-east-2",
  S3_BUCKET: "cardano-trusted-setup-test",
  S3_PREFIX: "Cardano-PPOT/",
  CEREMONY_POWER: "23",
  CEREMONY_ELLIPTIC_CURVE: "bls12-381",
};

// Global config paths
export const GLOBAL_CONFIG_DIR = join(homedir(), ".brebaje");
export const GLOBAL_CONFIG_PATH = join(GLOBAL_CONFIG_DIR, ".env");
export const LOCAL_CONFIG_PATH = ".env";

let configCache: BrebajeConfig | null = null;

/**
 * Check if the global config directory exists
 */
export function hasConfigDirectory(): boolean {
  return existsSync(GLOBAL_CONFIG_DIR);
}

/**
 * Ensure the global config directory exists
 */
export function ensureConfigDirectory(): void {
  if (!hasConfigDirectory()) {
    mkdirSync(GLOBAL_CONFIG_DIR, { recursive: true });
    console.log(`📁 Created global config directory: ${GLOBAL_CONFIG_DIR}`);
  } else {
    console.log(`📁 Directory already exists: ${GLOBAL_CONFIG_DIR}`);
  }
}

/**
 * Get the current config file path being used
 */
export function getConfigPath(): string {
  if (existsSync(GLOBAL_CONFIG_PATH)) {
    return GLOBAL_CONFIG_PATH;
  } else if (existsSync(LOCAL_CONFIG_PATH)) {
    return LOCAL_CONFIG_PATH;
  }

  return GLOBAL_CONFIG_PATH; // Default even if doesn't exist
}

/**
 * Check if global config exists
 */
export function hasGlobalConfig(): boolean {
  return existsSync(GLOBAL_CONFIG_PATH);
}

/**
 * Check if local config exists
 */
export function hasLocalConfig(): boolean {
  return existsSync(LOCAL_CONFIG_PATH);
}

/**
 * Create initial global config from template
 */
export function createInitialConfig(): string {
  // Try to find .env.example in CLI directory
  const possiblePaths = [".env.example", "../.env.example", join(process.cwd(), ".env.example")];

  for (const examplePath of possiblePaths) {
    if (existsSync(examplePath)) {
      return readFileSync(examplePath, "utf-8");
    }
  }

  // Fallback to minimal template
  return `# Brebaje CLI Global Configuration
# Generated by: brebaje-cli config new

# API Configuration
BREBAJE_API_URL=http://localhost:8067
BREBAJE_AUTH_TOKEN_PATH=~/.brebaje/token

# Perpetual Powers of Tau Ceremony Configuration
CEREMONY_POWER=23
CEREMONY_ELLIPTIC_CURVE=bls12-381

# AWS Configuration (for coordinators generating pre-signed URLs)
AWS_ACCESS_KEY_ID=your_aws_access_key_here
AWS_SECRET_ACCESS_KEY=your_aws_secret_key_here
AWS_REGION=us-east-1

# GitHub Token (for posting contribution records to gists)
GITHUB_TOKEN=ghp_your_github_token_here

# GitHub Fine-grained Token (for ceremony repository operations)
GITHUB_TOKEN_SCOPED=github_pat_your_fine_grained_token_here

# Ceremony Repository (for posting official contribution records)
CEREMONY_REPOSITORY_URL=https://github.com/owner/ceremony-repo

# Contributor Name (for ceremony contribution records)
CONTRIBUTOR_NAME=Your Full Name Here

# S3 Configuration (for coordinators)
S3_BUCKET=cardano-trusted-setup-test
S3_PREFIX=Cardano-PPOT/

# Auto-contribute configuration
# Use JSON file generated by 'brebaje-cli ppot generate-urls' command instead of environment variables
`;
}

/**
 * Load configuration from global location with fallback to local
 */
export function loadConfig(): BrebajeConfig {
  if (configCache) {
    return configCache;
  }

  ensureConfigDirectory();

  // Try loading from global config first
  if (existsSync(GLOBAL_CONFIG_PATH)) {
    dotenvConfig({ path: GLOBAL_CONFIG_PATH });
  } else if (existsSync(LOCAL_CONFIG_PATH)) {
    // Fallback to local config with migration warning
    console.log("⚠️  Using local .env file. Consider migrating to global config:");
    console.log(`   brebaje-cli config migrate`);
    dotenvConfig({ path: LOCAL_CONFIG_PATH });
  }

  // Build config object with defaults
  configCache = {
    BREBAJE_API_URL: process.env.BREBAJE_API_URL || DEFAULT_CONFIG.BREBAJE_API_URL,
    BREBAJE_AUTH_TOKEN_PATH:
      process.env.BREBAJE_AUTH_TOKEN_PATH || DEFAULT_CONFIG.BREBAJE_AUTH_TOKEN_PATH,
    CONTRIBUTOR_NAME: process.env.CONTRIBUTOR_NAME,
    GITHUB_TOKEN: process.env.GITHUB_TOKEN,
    GITHUB_TOKEN_SCOPED: process.env.GITHUB_TOKEN_SCOPED,
    AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_REGION: process.env.AWS_REGION || DEFAULT_CONFIG.AWS_REGION,
    S3_BUCKET: process.env.S3_BUCKET || DEFAULT_CONFIG.S3_BUCKET,
    S3_PREFIX: process.env.S3_PREFIX || DEFAULT_CONFIG.S3_PREFIX,
    CEREMONY_POWER: process.env.CEREMONY_POWER || DEFAULT_CONFIG.CEREMONY_POWER,
    CEREMONY_ELLIPTIC_CURVE:
      process.env.CEREMONY_ELLIPTIC_CURVE || DEFAULT_CONFIG.CEREMONY_ELLIPTIC_CURVE,
    CEREMONY_REPOSITORY_URL: process.env.CEREMONY_REPOSITORY_URL,
  };

  return configCache;
}

/**
 * Get a specific configuration value
 */
export function getConfig<K extends keyof BrebajeConfig>(key: K): BrebajeConfig[K] {
  const config = loadConfig();
  return config[key];
}

/**
 * Set a configuration value and persist to global config
 */
export function setConfig(key: keyof BrebajeConfig, value: string): void {
  ensureConfigDirectory();

  let configContent = "";

  // Read existing config if it exists
  if (existsSync(GLOBAL_CONFIG_PATH)) {
    configContent = readFileSync(GLOBAL_CONFIG_PATH, "utf-8");
  } else {
    // Create initial config from template
    configContent = createInitialConfig();
  }

  const lines = configContent.split("\n");
  const targetLine = `${key}=`;
  const newLine = `${key}=${value}`;

  let updated = false;
  const updatedLines = lines.map((line) => {
    if (line.startsWith(targetLine)) {
      updated = true;
      return newLine;
    }
    return line;
  });

  // If key doesn't exist, add it
  if (!updated) {
    updatedLines.push("", `# ${key}`, newLine);
  }

  writeFileSync(GLOBAL_CONFIG_PATH, updatedLines.join("\n"), "utf-8");

  // Clear cache to force reload
  configCache = null;
}

/**
 * Migrate local config to global config
 */
export function migrateLocalToGlobal(): void {
  if (!existsSync(LOCAL_CONFIG_PATH)) {
    throw new Error("No local .env file found to migrate");
  }

  if (existsSync(GLOBAL_CONFIG_PATH)) {
    throw new Error(`Global config already exists at ${GLOBAL_CONFIG_PATH}`);
  }

  ensureConfigDirectory();

  // Copy local config to global location
  const localContent = readFileSync(LOCAL_CONFIG_PATH, "utf-8");
  writeFileSync(GLOBAL_CONFIG_PATH, localContent, "utf-8");

  console.log(`✅ Migrated local config to ${GLOBAL_CONFIG_PATH}`);
  console.log(`💡 You can now remove the local .env file if desired`);

  // Clear cache to force reload
  configCache = null;
}

/**
 * Reset config to defaults
 */
export function resetConfig(): void {
  ensureConfigDirectory();

  const defaultContent = createInitialConfig();
  writeFileSync(GLOBAL_CONFIG_PATH, defaultContent, "utf-8");

  // Clear cache to force reload
  configCache = null;

  console.log(`✅ Reset config to defaults at ${GLOBAL_CONFIG_PATH}`);
}
