/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'get-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/README',
        {
          type: 'category',
          label: 'Authentication',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/auth',
            },
          ],
        },
        {
          type: 'category',
          label: 'Ceremonies',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/ceremonies',
            },
          ],
        },
        {
          type: 'category',
          label: 'Circuits',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/circuits',
            },
          ],
        },
        {
          type: 'category',
          label: 'Contributions',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/contributions',
            },
          ],
        },
        {
          type: 'category',
          label: 'Participants',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/participants',
            },
          ],
        },
        {
          type: 'category',
          label: 'Projects',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/projects',
            },
          ],
        },
        {
          type: 'category',
          label: 'Users',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/users',
            },
          ],
        },
        {
          type: 'category',
          label: 'Storage',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/storage',
            },
          ],
        },
        {
          type: 'category',
          label: 'Virtual Machines',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/vm',
            },
          ],
        },
        {
          type: 'category',
          label: 'Health',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/health',
            },
          ],
        },
        {
          type: 'category',
          label: 'Types',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/types',
            },
          ],
        },
        {
          type: 'category',
          label: 'Utilities',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/utils',
            },
          ],
        },
        {
          type: 'category',
          label: 'Application',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/app.controller',
            },
            {
              type: 'autogenerated',
              dirName: 'api/app.module',
            },
            {
              type: 'autogenerated',
              dirName: 'api/app.service',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security & Operations',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'security',
        },
      ],
    },
    // Manual documentation links
    {
      type: 'link',
      label: 'Setup Guide',
      href: '/docs/SETUP',
    },
    {
      type: 'link',
      label: 'Developer Guide',
      href: '/docs/DEVELOPER_GUIDE',
    },
    {
      type: 'link',
      label: 'Contributing',
      href: '/docs/CONTRIBUTING',
    },
    {
      type: 'link',
      label: 'TSDoc Guide',
      href: '/docs/TSDOC_GUIDE',
    },
  ],
};

module.exports = sidebars;
